### ISSUE TITLE
Org ReadMe

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#115]
### Related Tasks

SCRF Org Readme
https://github.com/smartcontractresearchforum/research_team/issues/248

🗪 [🚧] >Welcome #🏁start-here Branding
https://github.com/smartcontractresearchforum/engagement/issues/20

---

SCRF's [org ReadMe](https://github.com/smartcontractresearchforum/.github/blob/main/profile/README.md) is currently empty and needs to be populated. 

Elements to include

- [x] Full SCRF bio
- [x] Links to website, forum, all socials
- [x] Link to the Docs repo
- [ ]

**Comment by vsterling** [comment]
One idea is to have the Org ReadMe include outward-facing links to our sites and socials and point to our Docs repo. The ReadMe in the Doc repo will not have any social links but will be redirected back to the org ReadMe.

**Comment by SirAh0** [comment]
I really like the GitHub Org Readme.

https://github.com/github

It does a good job of mixing high level links into the copy and separating into clear sections. Also note, it isn't very long. It does a good job of leading people into a deeper dive for a given topic.

**Comment by marvino3** [comment]
> One idea is to have the Org ReadMe include outward-facing links to our sites and socials and point to our Docs repo. The ReadMe in the Doc repo will not have any social links but will be redirected back to the org ReadMe.

Makes senes to have that in one place. And agreed, I like the GitHub Org Readme as an example.

**Comment by vsterling** [comment]
@marvino3 and @SirAh0 Here is a first rough draft of an [Org ReadMe](https://docs.google.com/document/d/1f8jKzG4X5-ertjh-vQyZs5rOCrYj33C8mXDiM0xPdBU/edit?usp=sharing). Any thoughts so far?

**Comment by vsterling** [comment]
Also, in [GitHub's guide](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile), there are Public and Member readme views.

**Comment by SirAh0** [comment]
Sorry this missed my radar! Thank you so much for linking me, I'll be reviewing and get back to you soon!

**Comment by vsterling** [comment]
@ghettodev This organizational ReadMe is ready for review before I create a PR, if you would like to take a look and leave comments.

**Comment by SirAh0** [comment]
Has it been approved to post? Anything I can do to help move this forward?

**Comment by marvino3** [comment]
@isss111 please double check that this is ready to go - [Org Read Me](https://docs.google.com/document/d/1f8jKzG4X5-ertjh-vQyZs5rOCrYj33C8mXDiM0xPdBU/edit) and then let's add it as a PR

**Comment by isss111** [comment]
@marvino3 ready for your review and PR. Check: https://hackmd.io/@scrf/Skbf7-3Xj

**Comment by SirAh0** [comment]
Will review this with @marvino3  today!
