### ISSUE TITLE
SCRF Calendar links

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#123]
Copying request to update Calendar links from another [issue](https://github.com/smartcontractresearchforum/discovery/issues/119).

New Calendar
https://calendar.google.com/calendar/u/0/embed?src=null@scrf.io&ctz=America/Los_Angeles

We need to move to the SCRF.io domain and host new meeting urls.

Ensure all the documentation and old links are updates.

People:
@SirAh0

**Comment by vsterling** [comment]
@SirAh0 The [Connecting With SCRF](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_connecting_with_scrf.md) doc appears up to date.

I can update the [Weekly Community Calls](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_community_calls.md) doc, but this entire doc may need to be updated.

**Comment by SirAh0** [comment]
For reference, events are managed in the [SCRF Calendar of Events](https://github.com/orgs/smartcontractresearchforum/projects/30) PB

New events can be submitted here:
[Discovery Repo New Issue](https://github.com/smartcontractresearchforum/discovery/issues/new/choose) `📅 Add New Calendar Event`

**Comment by SirAh0** [comment]
https://github.com/smartcontractresearchforum/discovery/issues/119

has been completed

**Comment by SirAh0** [comment]
> I can update the [Weekly Community Calls](https://github.com/smartcontractresearchforum/docs/blob/main/en/content_community_calls.md) doc, but this entire doc may need to be updated.

Looks good! 

This is a good approach because meet URLs should only be listed on the event within the calendar.  

All the links shared within GitHub and elsewhere should link to the calendar and not the specific meet link.

**Comment by vsterling** [comment]
Links are updated.
