### ISSUE TITLE
Hiring - Offer email

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/discovery#126]

**Comment by ttaloute** [comment]
Hiring offer email template: https://docs.google.com/document/d/1F4cWvK3E7oSPdpPZDQcZAd1ETXNfWzgD8pMcA4BFUw0/edit

This is an email to be sent to new hires. Welcome suggestions on wording.

**Comment by marvino3** [comment]
@ttaloute I think this works!

**Comment by ttaloute** [comment]
@LorrettaGS check out the template Maria shared. @marvino3 , we can get started on expanding it to a template similar to this one. I really like it

**Comment by vsterling** [comment]
Hi @ttaloute Does this need to get posted anywhere or require further action from me?

**Comment by vsterling** [comment]
@ttaloute @LorrettaGS is there anything else we need to do? I can close this issue.

**Comment by vsterling** [comment]
Closing this issue, which can be reopened if the letter contents need to be revisited.

**Comment by ttaloute** [comment]
@zubepaul
