### ISSUE TITLE
SCRF Imagery (WS)

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#129]

**Comment by SirAh0** [comment]
Nice!

![image](https://user-images.githubusercontent.com/12703396/175387273-5a7a2049-ece4-4f00-ae53-08e21caa2b81.png)

Can we add some variety, web3 and crypto has a landscape of currencies and isn't necessarily dollar centric. DAI, ETH, BTC etc or generic crypto coin imagery if we don't want to use any specific logos.
