### ISSUE TITLE
Project Proposal Template

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#17]

**Comment by marvino3** [comment]
I think this is ready to go from a content perspective - needs a Dico edit/ reformat. In the templates section in the Discovery Drive - https://drive.google.com/drive/u/0/shared-drives

**Comment by vsterling** [comment]
@marvino3 I reformatted the template to no longer be a template embedded inside. If [this version](https://docs.google.com/document/d/1dZl-3wXLCW5N0OORUtV5CegMx7-TBYAp0ExbuBDSL0U/edit?usp=sharing) looks overall good to you, we can move on to editing the content more closely.

**Comment by marvino3** [comment]
@vsterling I added a few comments and revisions to ensure this is the template and aligned with how we've been using it

One note - there are three examples of project proposals referred to in the doc. The content is there but they do not fully follow this updated format. I think it would be great to include these and to ensure they are formatted based on this updated template.

**Comment by ralphlombreglia** [comment]
Read through the document and found nothing of substance to edit.

**Comment by vsterling** [comment]
[PR 60](https://github.com/smartcontractresearchforum/docs/pull/60) created

**Comment by vsterling** [comment]
Changes to the docs were made and resubmitted as [PR 63](https://github.com/smartcontractresearchforum/docs/pull/63). I just addressed the comments left. PR approval pending.

**Comment by isss111** [comment]
Hi @ralphlombreglia, can you please edit this document?
https://docs.google.com/document/d/1MjMcgKC-_x0RXFsSpv1upSMjKFM_-m74u1Gl9c-tyQc/edit#

**Comment by ralphlombreglia** [comment]
Hi @isss111, I've edited the document.

**Comment by isss111** [comment]
@marvino3 ready for PR: https://hackmd.io/@scrf/SkWQY4TVs

**Comment by isss111** [comment]
@SirAh0 we need to update the template gallery with the new Project Proposal Template:
https://docs.google.com/document/d/1MjMcgKC-_x0RXFsSpv1upSMjKFM_-m74u1Gl9c-tyQc/edit#

**Comment by marvino3** [comment]
This is ready to go @SirAh0 to add under Contributor Resources. We'll also want to update the Process doc link to the GitHub doc once that is uploaded.

**Comment by SirAh0** [comment]
> https://docs.google.com/document/d/1MjMcgKC-_x0RXFsSpv1upSMjKFM_-m74u1Gl9c-tyQc/edit#

done

**Comment by SirAh0** [comment]
> @SirAh0 we need to update the template gallery with the new Project Proposal Template:
> https://docs.google.com/document/d/1MjMcgKC-_x0RXFsSpv1upSMjKFM_-m74u1Gl9c-tyQc/edit#

done

**Comment by SirAh0** [comment]
> This is ready to go @SirAh0 to add under Contributor Resources. 

files added and updated. 

>We'll also want to update the Process doc link to the GitHub doc once that is uploaded.

Not clear: which process doc link?

**Comment by marvino3** [comment]
This one - https://github.com/smartcontractresearchforum/discovery/issues/208 but it is not yet ready to go. Still in the revision phase.

**Comment by SirAh0** [comment]
ok gotcha
