### ISSUE TITLE
Deal with Apple Imagery

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/discovery#173]
Have to wait until there's reception to access Apple Connect to fix the thumbnail.

**Comment by ivanplazacic** [comment]
Turned out to be complicated. Talking to Apple Support to figure it out.

**Comment by marvino3** [comment]
oh wow, any updates @ivanplazacic?

**Comment by ivanplazacic** [comment]
Not as of yet. Apple Connect seems to be showing new assets but it doesn't seem changed on Apple Podcasts. Waiting for @eleventh19 to re-send the invitation for managing the podcast, hoping that, since my Apple ID issues are fixed, it might give me more options. If that doesn't help, I'll get in touch with Apple Media Services again.

**Comment by ivanplazacic** [comment]
Finally managed to change the main one. The episodes should follow automatically. Once that's done too, I'll mark this as done.
