### ISSUE TITLE
SourceCred and Chat Patterns/ Templates

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#175]
Description: Create patterns and templates we can use for SourceCred and Chat Guild Community videos as they are posted to Youtube.

**Comment by zubepaul** [comment]
Looks great! I generally approve, but just want to make sure that the level of SC logo repurposing would be acceptable to that community. I suspect that it is, but just want to make sure we have done our due diligence.

**Comment by marvino3** [comment]
Nice agreed, is that something you could check on @zubepaul? cc me on the email for any F/Us?

**Comment by marvino3** [comment]
@zubepaul any updates here? Are we good to move forward w the SC imagery?

**Comment by zubepaul** [comment]
@marvino3 From what I can tell, this should be ok with the SC community.

**Comment by marvino3** [comment]
The Chat and SC socials templates are created. Can be found [here](https://drive.google.com/drive/folders/1W0VhG5Edci7rm2fC_QzxQEftuv-Pu5R0?usp=sharing)

The thumbnails for the chat and SC guild videos are still being worked on @MattDesigner

**Comment by MattDesigner** [comment]
https://drive.google.com/drive/folders/1y7Luvkwip9W9WQ-SNtwenUW2tVxgWUxw?usp=sharing

Designs for Community Chat Guild and Sourcecred Chat Guild are here. 

Not sure if we are using screen grabs for the Sourcecred thumbnail image? So there are two designs in the pdf - one with space for a screen grab and another which uses figures similar to those on the scrf.io website in the shape of the Sourcecred logo.

**Comment by MattDesigner** [comment]
https://drive.google.com/drive/folders/1rP3AD7C3KtAF4_rjXzqVEY36BtP9vTkh?usp=sharing

Community Chat Guild / Sourcecred Guild Editable Templates
