### ISSUE TITLE
SC Guild Meetings

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/discovery#180]

**Comment by marvino3** [comment]
Q: What guilds do we want to be posting and why? @zubepaul

**Comment by SirAh0** [comment]
I think the SourceCred ones for sure. 

Just as a side note, all the videos are available to view publicly from the google calendar events. Click **More Details**.

https://scrf.io/calednar
 
![image](https://user-images.githubusercontent.com/12703396/189826175-abd78b15-31da-427e-87e8-126b9151f624.png)

**Comment by zubepaul** [comment]
@SirAh0 @marvino3 
I believe that both the Chat and Sourcecred guild are ready for recorded meetings to be public. We'll make sure that we mention that before recording though. Could they be put in a playlist?

**Comment by ivanplazacic** [comment]
Yes. The question is do we want an all-encompassing playlist for all the guilds or do we want separate: SourceCred, Chat, etc?

**Comment by marvino3** [comment]
Sounds good and yes @zubepaul. Let's make them separate @ivanplazacic because the content is quite different for a SC meeting vs a Chat meeting and people may want to view everything around SC, etc.

**Comment by ivanplazacic** [comment]
Link to the SourceCred playlist:

https://youtube.com/playlist?list=PLM6XYWcweAF3QGK036NID2LQohM5Ote0H

**Comment by SirAh0** [comment]
Are the videos public? I can't seem to view them

![image](https://user-images.githubusercontent.com/12703396/196283650-e0178a5c-f778-4b65-8eab-50bbd77d3ae4.png)
