### ISSUE TITLE
SCRF Governance Implementation Panel Transcript

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#183]
[SCRF Governance Implementation Panel Transcript](https://docs.google.com/document/d/1f5HYBDYjRWEAtvF3yZkgBdHGztX26d9ho_HTrklraAc/edit?usp=sharing)

Add to Docs Directory

**Comment by isss111** [comment]
Link to hackMD: https://hackmd.io/@scrf/HkLVUkoXo

**Comment by marvino3** [comment]
Ready to go. @SirAh0 this would go under the transcripts section on the Docs Directory.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/197888180-aa8f261f-9aa1-421d-9590-d18fa2dc15a6.png)

https://github.com/smartcontractresearchforum/docs/blob/main/en/transcripts/scrf_governance_implementation_panel_transcript.md
