### ISSUE TITLE
SCRF Governance Theory Panel Transcript

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#184]
[SCRF Governance Theory Panel Transcript](https://docs.google.com/document/d/1PRTJn3chQeTi9dR2_b9m5gXpTkSfHcmY0G8plcOzRXE/edit?usp=sharing)
Add to Docs Directory

**Comment by isss111** [comment]
Here's the link for hackMD: https://hackmd.io/@scrf/ByH_mJjmi

**Comment by marvino3** [comment]
Looks good. @SirAh0 can you please a Transcripts section to the Docs Directory at the bottom and add this there?

**Comment by marvino3** [comment]
Posted
