### ISSUE TITLE
SCRF Identity and Reputation Panel Transcript

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#185]
[SCRF Identity and Reputation Panel Transcript](https://docs.google.com/document/d/1b5MaoHyyJV9Qb6kR8S4f-3irYqcTNF_7eKACTqtDuVI/edit?usp=sharing)

Add to Docs Directory

**Comment by isss111** [comment]
Link to hackMD: https://hackmd.io/@scrf/BJ2oNysXj

**Comment by marvino3** [comment]
Ready to go. @SirAh0 this would go under the transcripts section on the Docs Directory.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/197890744-f8c63de7-d9af-4bfa-bf7d-d1681eb92aab.png)

https://github.com/smartcontractresearchforum/docs/blob/main/en/transcripts/scrf_identity_and_reputation_panel_transcript.md
