### ISSUE TITLE
SCRF Privacy and SNARKS Panel Transcript

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#186]
[SCRF Privacy and SNARKS Panel Transcript](https://docs.google.com/document/d/18Z3Lk_aBKlG3fLkwnKkGmkQghaYE3xGAHyIwGV1rtkA/edit?usp=sharing)

Add to Docs Directory

**Comment by isss111** [comment]
Link to HackMD: https://hackmd.io/@scrf/H1XIByjQs

**Comment by marvino3** [comment]
Ready to go. @SirAh0 this would go under the transcripts section on the Docs Directory.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/197889687-3a041cdb-8eef-47fd-93b4-9d2175af66bc.png)


https://github.com/smartcontractresearchforum/docs/blob/main/en/transcripts/scrf_privacy_and_snarks_panel_transcript.md
