### ISSUE TITLE
SCRF Central Bank Digital Currency (CBDC) Transcript

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#187]
[SCRF Central Bank Digital Currency (CBDC) and Blockchain Panel Transcript](https://docs.google.com/document/d/1EFYlJ2Vhc8yDFPjJmbS7BIDmCzlWeTY10LAk6WjUs5U/edit?usp=sharing)

Add to Docs Directory

**Comment by isss111** [comment]
Link to HackMD: https://hackmd.io/@scrf/ByYkv1jXi

**Comment by marvino3** [comment]
Ready to go. @SirAh0 this would go under the transcripts section on the Docs Directory.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/197890043-07baaf2f-4e85-4862-b0f0-94a3fe46b454.png)

https://github.com/smartcontractresearchforum/docs/blob/main/en/transcripts/scrf_central_bank_digital_currency_cbdc_and_blockchain_panel_transcript.md
