### ISSUE TITLE
Docs Directory

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#199]
A [first version](https://docs.google.com/document/d/1f35eitYxubmidOGcgSHyFuGCjrJIZAnAxusz_1Sh68o/edit?usp=sharing) of the Docs Directory is ready to add to GitHub.

I call this the mini version because it only includes docs already live on the Docs GitHub repo.

**Comment by SirAh0** [comment]
Ok - I'm available any time today to chat about implementing this. It should go quick!

**Comment by vsterling** [comment]
[PR 58](https://github.com/smartcontractresearchforum/docs/pull/58) submitted
