### ISSUE TITLE
SCRF.io project plan doc

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#2]
[Project Plan Doc](https://docs.google.com/document/d/13o9cY3TOr9T3rKg3qcHHECnQqiTo8Vz2pfOVMNoHjdk/edit?usp=sharing)

[Technical Doc](https://docs.google.com/document/d/1VyXvDChESbrDQMKZK3ouzJqEz5v0MyOnZIRqFdYrSZw/edit#heading=h.2oztxqcw41zm)

**Comment by SirAh0** [comment]
Adrian and I will be updating the technical doc this week
