### ISSUE TITLE
Socials Ideation GitHub Board

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#203]
Description: Create a board to capture Socials/ Content Marketing Ideas to replace the [SCRF Social Media Content](https://docs.google.com/spreadsheets/d/1C68ppXZNjI-g_dRsmGK7WD7ylj9jhHGe/edit?usp=sharing&ouid=101449646249969214622&rtpof=true&sd=true) spreadsheet. 

- Posts may go on Twitter, LinkedIn, YT, etc. 
- Statuses can mirror the Disco board - Idea, To Do, In Progress, Done, Closed
- The Issue info can leverage the columns from the Socials spreadsheet
- Create a tag for timeliness aka evergreen vs topical

- [x] Create the Socials Content board
- [x] Relevant categories
- [x] Relevant tags
- [ ] Issue Template

**Comment by MichaelSCRF** [comment]
Socials Ideation GitHub Board is updated at the following link: https://github.com/orgs/smartcontractresearchforum/projects/41/views/3

**Comment by MichaelSCRF** [comment]
@marvino3 and @ralphlombreglia: I created the following labels for the Socials Content repo:

twitter
linkedin
evergreen
time sensitive

You can utilize these labels within the issue to indicate which channel(s) an issue is for, as well as whether a piece of content is evergreen or is time-sensitive and needs to be prioritized for publication.

**Comment by MichaelSCRF** [comment]
Will create a separate issue for the Issue Template checkpoint and update that here.

**Comment by MichaelSCRF** [comment]
Created a separate issue for the [Socials Issue Template](https://github.com/smartcontractresearchforum/discovery/issues/271) and am closing this issue out now, @marvino3.
