### ISSUE TITLE
Minecraft will block NFT integration

### ISSUE THREAD

**Issue by MichaelSCRF** [smartcontractresearchforum/discovery#210]
# Content
> @Minecraft recently announced that “integrations of #NFTs with Minecraft" will not be allowed. https://www.minecraft.net/fi-fi/article/minecraft-and-nfts
> 
> Read @ntnsndr’s @SCRForum post on @MinetestProject, a game similar to Minecraft but with self-governance, not autocracy, built-in. https://www.smartcontractresearch.org/t/1195
> 

# URLs
https://www.minecraft.net/fi-fi/article/minecraft-and-nfts
https://www.smartcontractresearch.org/t/1195

# Task List
- [ ] #211

**Comment by MichaelSCRF** [comment]
- [ ] Schedule this post in Loomly for Tuesday, July 27 @MichaelSCRF

**Comment by SirAh0** [comment]
![Image](https://user-images.githubusercontent.com/12703396/180488081-0ae32877-60ab-4b0f-9b63-4163705ea371.png)

**Comment by SirAh0** [comment]
![Image](https://user-images.githubusercontent.com/12703396/180488135-575289a7-8b65-45f6-a8a7-91e22b385d13.png)

**Comment by SirAh0** [comment]
https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg
