### ISSUE TITLE
📅 - Impact Networks Reading Group

### ISSUE THREAD

**Issue by ufkhan97** [smartcontractresearchforum/discovery#233]
### ◾Title◾

Impact Networks Reading Group (Part 2) 

### Start Time◾

August 24th, 2022 8 AM PT

### Cadence

Once

### Duration

1 hour

### Location

https://forms.gle/X4YrtQgYFDbsRiVG6

### ◾Description◾

Goal: Discuss Part 2 of Impact Networks in the context of SCRF and our mission

- [Register Here for a Calendar Invite](https://docs.google.com/forms/d/1rczuXOwcOtRV6bkIWwSILz22pTDrua_y4P9JTnxX-yo/edit)
- [More Info](https://www.smartcontractresearch.org/t/reading-group-impact-networks-june-27th-community-call-june-30th/1628/8 )

**Comment by SirAh0** [comment]
Live on google calendar and as a discord event
