### ISSUE TITLE
Web3 Conference Videos

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/discovery#236]

**Comment by marvino3** [comment]
@ivanplazacic is creating the web3 videos
once these are created @eleventh19 is checking to ensure people opt-in around the posting of the videos

**Comment by ivanplazacic** [comment]
Location of edited files:

https://drive.google.com/drive/folders/1-hzokq0VhODDI4qTbbPbm_iC3B6rtpFM?usp=sharing

YT playlist:

https://youtube.com/playlist?list=PLM6XYWcweAF1kn6GTUW0UhjLcDPzBgpGN
