### ISSUE TITLE
Converting Google Docs to Markdown

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#253]
## Links
Google Doc: [Converting Docs to Markdown](https://docs.google.com/document/d/11D9naf9OxXXi8Bexrr_QZpBgAuiERuABTVJz4HqLBsI/edit?usp=sharing)

## Next Steps
- [ ] Add to the directory

**Comment by vsterling** [comment]
@ralphlombreglia  This is an internal doc only but is ready to be edited before going on the directory.

**Comment by ralphlombreglia** [comment]
@vsterling: I've edited this doc and moved it to the Final Edit column in SCRF Messaging.

**Comment by marvino3** [comment]
@isss111 doc looks ready to go from a content perspective

**Comment by isss111** [comment]
@marvino3 here is the link to the hackMD https://hackmd.io/@scrf/r1dkO5KQj ready to be uploaded to Github.

**Comment by marvino3** [comment]
Thanks Inês. This doc looks good to go.
@SirAh0 could you please create a new SCRF Documentation section on the Docs Directory below Forum Templates and above Ref Materials and add this there?

**Comment by SirAh0** [comment]
done!

![image](https://user-images.githubusercontent.com/12703396/197886194-9c13ad7a-ba48-4666-aff3-e8e1d9d7dddf.png)

https://github.com/smartcontractresearchforum/docs/blob/main/en/doc_directory.md
