### ISSUE TITLE
Web3 Glossary

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#254]
## Links
Google Doc: [Web3 Glossary](https://docs.google.com/document/d/1BQOo818qJfV-qlvku9BmIFCm_9e5XI7SvUWt4zisC9c/edit?usp=sharing)
GitHub: [Web3 Terms Glossary](https://github.com/smartcontractresearchforum/docs/blob/main/en/reference_terms_glossary.md)

## Next Steps
- [ ] Update GitHub content

**Comment by vsterling** [comment]
@ralphlombreglia this shouldn't need many edits and just needs a final look through.

**Comment by ralphlombreglia** [comment]
@vsterling I did my edits in the Google doc, not the Github doc.

**Comment by isss111** [comment]
@marvino3 who worked on this document originally? There are a few questions from @ralphlombreglia that need answers.

**Comment by isss111** [comment]
@marvino3 I found some alternative links for the ones that were down. It would be great to have feedback on the questions/suggestions Ralph left in the document.

**Comment by isss111** [comment]
@marvino3 ready for PR: https://hackmd.io/@scrf/SJle_VD9Hs

**Comment by marvino3** [comment]
This is ready to go @SirAh0. We want to remove the old Web3 Glossary from the Table of Contents under 'Forum' and add this under a 'Web3' section at the bottom of the page. It would also replace the 'Terms Glossary' under 'Web3 Ref Materials' on the Docs Directory.
