### ISSUE TITLE
SCRF Terms and Titles

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#26]
[SCRF Terms and Titles](https://docs.google.com/document/d/1_6v1vVUEV12UpSP8hN0Fq-TmvgHWEIejuiv6Cz1h23E/edit?usp=sharing)

Brief Description: SCRF Glossary of Terms and Titles to be used when referring to terms at SCRF

**Comment by vsterling** [comment]
@marvino3 What's the status on the terms and titles?

**Comment by SirAh0** [comment]
This section seems redundant. 
> Getting Work Done in These Roles

Unless I am reading it wrong, the information is defined in the following section **Tooling - User Access Roles**

The Tooling - User Access Roles section is still a WIP but I'm not sure when it will actually be fully complete. It's something I will be updating over time so probably not worth holding up the launch of the document for that section.

**Comment by ralphlombreglia** [comment]
@marvino3 @vsterling Made light edits to this Fri, July 8, 2022.

**Comment by marvino3** [comment]
I think the content is there. A few notes:
- For format, I think some of the headings may be off in terms of h1, h2, etc so please double-check. We want to run this doc through Visual Studio Code to fix other markdown errors and ensure the tables translate over.
- Punctuation may be inconsistent - seems like some places have periods at the end, some don't. 
- For grammar, I think this would be worth running through Grammarly for a final pass

**Comment by isss111** [comment]
@marvino3 ready for PR: https://hackmd.io/@scrf/HJWeO4aNo

**Comment by marvino3** [comment]
This is ready to go @SirAh0
