### ISSUE TITLE
📅 - Coffee House Live

### ISSUE THREAD

**Issue by jring-o** [smartcontractresearchforum/discovery#267]
### ◾Title◾

Coffee House Live

### Start Time◾

10am

### Cadence

Every Thursday

### Duration

60 minutes

### Location

https://discord.com/channels/784234332617048065/992196359157461093

### ◾Description◾

Come talk about the ideas behind research posted to SCRF! 

A new topic is chosen every week and discussions will be informed by research related to that topic. But don't worry! You don't need to read any research to participate in the discussion. Just grab yourself a cup of coffee and let's talk about the technology we love!

Want to lead a discussion? You can! Just let us know,

**Comment by SirAh0** [comment]
added to
- discord native event
- scrf gcal
- sesh bot for #events channel
