### ISSUE TITLE
Newsworthy Web3 Projects

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#273]
This is a general idea and not yet a fleshed out post. 
@zubepaul had the idea of promoting newsworthy projects and encouraging folks to come post on the forum. 
Aka encourage posts like the SC one - https://www.smartcontractresearch.org/t/flying-the-sourcecred-plane/1873

Next steps would be to brainstorm what this could entail

**Comment by zubepaul** [comment]
Will this need a project proposal? Can get started on that week of August 22, 2022

**Comment by marvino3** [comment]
@zubepaul that would be awesome. Feel free to jam on it with @MichaelSCRF in my absence if you get a chance. I'd love to then collaborate on this further in Sept.

**Comment by MichaelSCRF** [comment]
Thanks for the update on this! @zubepaul, let's chat about this during today's meeting, and please feel free to ping with me in the meantime if you have any questions or need any feedback on the project proposal.

**Comment by marvino3** [comment]
Moved to the Disco board
