### ISSUE TITLE
scrf.io Showcase Images

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#276]
Based on Highlight Reels - https://docs.google.com/document/d/1ltEO55gQmNiEi0ZQb3bkEoYvVR0ySlPNdVCOD-TNBNI/edit?usp=sharing

**Comment by marvino3** [comment]
@MattDesigner the projects and images were approved. Please create a high-res version of the three remaining project images similar to the event ones for nathan, seth, and metagov projects. 

These will live in the showcase section on scrf.io

**Comment by MattDesigner** [comment]
@SirAh0 The 3 new showcase images are in the folder here
https://drive.google.com/drive/folders/1cPj7-MeOjKf1eLipAqff04T1ammWv1PS?usp=sharing

Let me know if you have any issues.

**Comment by SirAh0** [comment]
thank you
