### ISSUE TITLE
Writing Style Guide

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#280]
Changing title in ReadMe to "Writing Style Guide"

**Comment by marvino3** [comment]
@SirAh0 can you please fix the "Writing Style Guide" title to say "Writing Style Guide". It currently says "[Writing and Style Guide](https://github.com/smartcontractresearchforum/docs/blob/main/en/reference_style_guide.md)

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/196488893-c9d77bd9-8578-487e-af1f-00d73855ddf0.png)
