### ISSUE TITLE
Mastercard and Binance join forces to let customers in Argentina pay directly with crypto

### ISSUE THREAD

**Issue by ralphlombreglia** [smartcontractresearchforum/discovery#284]
# Twitter Content
(1/2) For #crypto news that’s a double-edged sword, note that #Mastercard & #Binance have teamed up to let crypto holders in Argentina directly pay >90M merchants worldwide. A great thing for crypto adoption, but what about #privacy & #decentralization?

https://www.mastercard.com/news/latin-america/en/newsroom/press-releases/pr-en/2022/august/binance-and-mastercard-launch-prepaid-card-in-argentina-to-bridge-cryptocurrencies-and-everyday-purchases/

(2/2) For an interesting take on #tradfi meeting #crypto, see Amit Agarwal’s summary of his talk on #netting — the process of combining all payments owed between two parties to one net payment — in “Privacy Preserving Decentralized Netting” on @SCRForum. https://www.smartcontractresearch.org/t/1782

# LinkedIn Content
For crypto news that’s a doubled-edged sword, consider that Mastercard and Binance have teamed up to enable crypto holders in Argentina to pay >90M merchants worldwide. A great thing for crypto adoption, but what about privacy and decentralization?

https://www.mastercard.com/news/latin-america/en/newsroom/press-releases/pr-en/2022/august/binance-and-mastercard-launch-prepaid-card-in-argentina-to-bridge-cryptocurrencies-and-everyday-purchases

Then see an interesting take on traditional finance meeting crypto: Amit Agarwal’s summary of his talk on netting — the process of combining all payments owed between two parties into one net payment — in “Privacy Preserving Decentralized Netting” on the SCRF Forum. https://www.smartcontractresearch.org/t/1782

# URLs
https://www.mastercard.com/news/latin-america/en/newsroom/press-releases/pr-en/2022/august/binance-and-mastercard-launch-prepaid-card-in-argentina-to-bridge-cryptocurrencies-and-everyday-purchases

https://www.smartcontractresearch.org/t/1782

# Task List

**Comment by ralphlombreglia** [comment]
@marvino3 @MichaelSCRF The post "Mastercard and Binance join forces to let customers in Argentina pay directly with crypto" [#284](https://github.com/smartcontractresearchforum/discovery/issues/284) has been posted to Socials Content as of Friday, August 26, 2022, 3:05:50 PM PT.

**Comment by SirAh0** [comment]
You can use the following form to create short urls. Would be perfect to use for these kinds of posts.

www.scrf.io/get-a-short-url

Let me know if you have any questions!

**Comment by MichaelSCRF** [comment]
@SirAh0, thanks so much, this is great! I'll plan on using this for longer links to external news stories like this. The only potential issue I see is that it might impact the social graphs that populate on the socials channels based on the coding of the source pages, but I can always trial and error this before I post anything.
