### ISSUE TITLE
📅 - Infinite Machine Reading Group Second Half

### ISSUE THREAD

**Issue by ufkhan97** [smartcontractresearchforum/discovery#292]
### ◾Title◾

Infinite Machine Reading Group Second Half

### Start Time◾

6 AM PDT 

### Cadence

Once

### Duration

90 Minutes 

### Location

https://meet.google.com/puc-xzwn-gnk

### ◾Description◾

In this SCRF reading group session, we'll be discussing the second half of Camila Russo's book The Infinite Machine. The suggested reading is parts 3-6, from page 182 to the end.

https://www.smartcontractresearch.org/t/reading-group-the-infinite-machine/1988

**Comment by SirAh0** [comment]
done

Google Calendar
https://scrf.io/calendar

Discord Link
https://discord.gg/ppbtkSfW?event=1019135581135044639
