### ISSUE TITLE
SCRF Brand Messaging Guide

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#309]
GDoc link: https://docs.google.com/document/d/1q4t_Buo66gfL7YA4Uu-1t8ptAhy5smMzVvku8orYx2E/edit

**Comment by isss111** [comment]
Ready for PR: https://hackmd.io/@scrf/B1ppJvcSi

See comment above for directions.

**Comment by marvino3** [comment]
Thanks Ines. I think this issue is ready to be closed now that the doc is in hackmd. After further consideration, think we want to keep this doc off of the docs directory to avoid confusion.
