### ISSUE TITLE
How to get compensated

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/discovery#31]
Hi Team,

A separate documentation on "how to get compensated if you are receiving a (research summary) grant" would be very appreciated for several reasons:

1. Ensure necessary information will be presented in the invoice:

- Which grant program did they went through/are they starting (and thus how much was the total grant amount)
- Which paper did they summarize
- How many % of the grant is already given out to them (currently it could be 0%, 20%, 30%)
- How much more % of the grant are you requesting this time (70%, 80%, or 100%)

2. Ask them to 

- Either register Request with the name they are interacting with SCRF, or provide their name somewhere in the invoice
- Be sure to check with the content team that the summary is at a stage that can be billed
- Combine the invoice with other invoices (suppose they were also on another paid-by-the-hour role at SCRF, we ask people to  send only one invoice instead of one each for the grant and hour sheet)

3. Provide more color around how soon they are expected to get paid

- When does the mid-month billing cycle take place
- Who to contact for more information around that

**Comment by vsterling** [comment]
Adding a section in [How to get compensated](https://docs.google.com/document/d/1aO0TL7lXunZZFymukb4BgLa5EaqVLVKbE3qoiffke4M/edit?usp=sharing) for researcher's requesting grants.

**Comment by vsterling** [comment]
@vsterling Need to incorporate these updates ASAP

**Comment by vsterling** [comment]
@twan-dev @eleventh19 I modified the [How to Get Compensated](https://docs.google.com/document/d/1aO0TL7lXunZZFymukb4BgLa5EaqVLVKbE3qoiffke4M/edit?usp=sharing) doc to include a section for researchers and updated billing cadence. I tagged you both in comments where relevant changed need your approval.

**Comment by twan-dev** [comment]
@vsterling Just left some comments.

**Comment by twan-dev** [comment]
Turned on suggestion mode and left some edits today.

**Comment by vsterling** [comment]
Thanks @twan-dev I'll take a look, and have some edits I need to make from the Discovery side.

**Comment by marvino3** [comment]
Hey @twan-dev and @vsterling, we want to have two separate docs - one is our general How to get compensated for work doc, and the other is a grant-specific comp guide. The reason being is we want to have a doc that encompasses How to get comped for the entire org, including PT and FT, and not just grants. 

If we want to have an additional doc for Grants compensation bc that entails more info, awesome, let's create a separate doc for that and refer to it in the general How to get comped doc. Let me know if you have any questions.

**Comment by vsterling** [comment]
Hi @ralphlombreglia this [How to Get Compensated](https://docs.google.com/document/d/1aO0TL7lXunZZFymukb4BgLa5EaqVLVKbE3qoiffke4M/edit?usp=sharing) doc is ready for editing. Note to all: we are creating a separate guide for bounty payments.

**Comment by ralphlombreglia** [comment]
Hi @vsterling, I've edited this document in Suggestion mode.

**Comment by vsterling** [comment]
[PR 64](https://github.com/smartcontractresearchforum/docs/pull/64) created.

**Comment by vsterling** [comment]
resubmitted changes to the PR
