### ISSUE TITLE
discord 5

### ISSUE THREAD

**Issue by okoba** [smartcontractresearchforum/discovery#335]
Take a deep dive into web3 research discussions/summary while you earn source creds.

  1. How can knowledge regarding DAO platforms be captured and organized systematically to support decentralized autonomous organizations with the decision-making process? to get a sublime response, click the link below; https://www.smartcontractresearch.org/t/research-summary-a-decision-model-for-decentralized-autonomous-organization-platform-selection-three-industry-case-studies/1157[]
  2. The researcher suggests a framework for open-access, distributed machine learning algorithms that use common frameworks and databases without centralized data processing techniques. Click the link to find out more about machine learning algorithms; https://www.smartcontractresearch.org/t/research-summary-leveraging-blockchain-for-greater-accessibility-of-machine-learning-models/808[]
    3 .The authors end by posing research queries about topics including the market value of tokens with similar governance functions, the legal viability of DeFi business models, and more. Click the following link to learn more about DEFI protocols' revenue stream: (https://www.smartcontractresearch.org/t/research-summary-a-short-survey-on-business-models-of-decentralized-finance-defi-protocols/1947
 4.Many privacy-enhancing overlays have been implemented, including noncustodial, trustless currency mixers, and confidential transactions, according to the post "Blockchain is watching you." Click the link to interact with co-author Chris Bate  on his brilliant summary, (https://www.smartcontractresearch.org/t/research-summary-blockchain-is-watching-you-profiling-and-deanonymizing-ethereum-users/564
     5. Through a thorough comparative examination of the leading NFT marketplaces, the study looked into security in both the NFT marketplaces and the larger NFT ecosystem. to discover more about the absence of seller/buyer verification, counterfeiting, and other (issues;https://www.smartcontractresearch.org/t/research-summary-understanding-security-issues-in-the-nft-ecosystem/1350))

**Comment by okoba** [comment]
@zubepaul @MichaelSCRF

**Comment by zubepaul** [comment]
@okoba Please replace the NFT thread with this one instead
https://www.smartcontractresearch.org/t/research-summary-collaborative-learning-for-cyberattack-detection-in-blockchain-networks/2140

**Comment by okoba** [comment]
Hi Paul, 
Just seeing this . Should I still do it ?

**Comment by zubepaul** [comment]
No need. We will promote it separately. In the future, please provide for a period of feedback before posting and closing.
