### ISSUE TITLE
Industry Template Discussion Post

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#336]
https://hackmd.io/@content/BJ-Roatfo

**Comment by marvino3** [comment]
@isss111 FYI we want to have a working draft of this document that we could share publicly by EOW. I will try and take a look it from a content standpoint later today. Either way, let's discuss this as a priority tomorrow.

**Comment by marvino3** [comment]
Created a gdoc for revisions - https://docs.google.com/document/d/1ZEdlK97pyHmI-RDIfqhWPZgO0Pm5zIDSj7imFt2UW70/edit?usp=sharing

**Comment by marvino3** [comment]
Meeting with @twan-dev on 10/5 to review the doc

**Comment by isss111** [comment]
Hi @ralphlombreglia ! This document is ready for editing:
https://docs.google.com/document/d/1ZEdlK97pyHmI-RDIfqhWPZgO0Pm5zIDSj7imFt2UW70/edit#

**Comment by ralphlombreglia** [comment]
Hi @isss111. I found nothing in the template that needed editing. Good to go, IMO.

**Comment by isss111** [comment]
@marvino3 ready for PR: https://hackmd.io/@scrf/r1FyDuUHi

**Comment by marvino3** [comment]
Posted
