### ISSUE TITLE
Discovery Strategy Docs

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#343]

**Comment by MichaelSCRF** [comment]
@marvino3, here are the links to the Strategy Documents. Please let me know if there are any additional documents that are missing from this list.

- [Research Pulse Newsletter Project Proposal](https://docs.google.com/document/d/1_wIk9211K3DtPvXnH6OYctki6IrAv51rzgDQFC0q_YQ/edit#)
- [Research Pulse Newsletter Exploratory Document](https://docs.google.com/document/d/1q0PRG9kxJuZTnxnjigJJuItf7siZrfLR4S7wp8JcuoU/edit#heading=h.u805iidwthoc)
- [SCRF Twitter Strategy and Process 2022](https://docs.google.com/document/d/1Ucc_-4z9JZrR6kud5RpVqYsfsjaOb9UHarhX1-DYFSU/edit#heading=h.ks6kuvnmzzp1)
- [SCRF LinkedIn Strategy and Process 2022](https://docs.google.com/document/d/1EmDNWlYy1HdmbAbKKWdnHiTW43v-QJXKybxcen5MqIw/edit#heading=h.ks6kuvnmzzp1)
- [SCRF YouTube Strategy](https://docs.google.com/document/d/1uiD0KF7orMsw2w_Vyl6Oif3KX5BCOeEHTGH2biKvSB4/edit#heading=h.dgopc9jfqrst)
- [Project Proposal Template - SOCIAL MEDIA STRATEGY](https://docs.google.com/document/d/1suoQtgnJpA4LqahyPYpTy4_qCEw_7hEWZahgMrnx6YM/edit#heading=h.9xvwuxmfaxqg)
- [SCRF Event Planning Rubric](https://docs.google.com/document/d/1LAvZKe-0U1hiXdAKVCdG-0yT-Ts9k8DtkMWvg_ramPE/edit#heading=h.envdopv05nww)

**Comment by isss111** [comment]
@marvino3 this looks like a brainstorming document: [Research Pulse Newsletter Exploratory Document](https://docs.google.com/document/d/1q0PRG9kxJuZTnxnjigJJuItf7siZrfLR4S7wp8JcuoU/edit#heading=h.u805iidwthoc)

Do we want to upload it to GitHub?

**Comment by isss111** [comment]
@marvino3 I requested access to most of the documents above.

**Comment by marvino3** [comment]
> @marvino3 this looks like a brainstorming document: [Research Pulse Newsletter Exploratory Document](https://docs.google.com/document/d/1q0PRG9kxJuZTnxnjigJJuItf7siZrfLR4S7wp8JcuoU/edit#heading=h.u805iidwthoc)
> 
> Do we want to upload it to GitHub?

One the Project Proposal doc, not this exploratory one. Thanks!

**Comment by isss111** [comment]
@MichaelSCRF Can you please give me access to the documents above? My email is ines@scrf.io. Thanks!

**Comment by isss111** [comment]
@marvino3 I haven't heard from Michael. Do you mind sharing the documents below with me?

[SCRF Twitter Strategy and Process 2022](https://docs.google.com/document/d/1Ucc_-4z9JZrR6kud5RpVqYsfsjaOb9UHarhX1-DYFSU/edit#heading=h.ks6kuvnmzzp1)
[SCRF LinkedIn Strategy and Process 2022](https://docs.google.com/document/d/1EmDNWlYy1HdmbAbKKWdnHiTW43v-QJXKybxcen5MqIw/edit#heading=h.ks6kuvnmzzp1)
[SCRF YouTube Strategy](https://docs.google.com/document/d/1uiD0KF7orMsw2w_Vyl6Oif3KX5BCOeEHTGH2biKvSB4/edit#heading=h.dgopc9jfqrst)
[Project Proposal Template - SOCIAL MEDIA STRATEGY](https://docs.google.com/document/d/1suoQtgnJpA4LqahyPYpTy4_qCEw_7hEWZahgMrnx6YM/edit#heading=h.9xvwuxmfaxqg)

**Comment by marvino3** [comment]
You got it, just shared all of those with you. Lmk if you need access to any others.

**Comment by isss111** [comment]
@marvino3 each one of these documents is already following the documentation process. I believe this issue can be closed.

**Comment by marvino3** [comment]
agreed, thanks
