### ISSUE TITLE
SCRF Moderator Guidelines

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#363]
GDoc link: https://docs.google.com/document/d/1jr9ghzf0kIUPrD0ASVwbbLfIJ817YNgZaeoO-hXvItA/edit

**Comment by isss111** [comment]
@SirAh0 can we add emojis to markdown?

**Comment by SirAh0** [comment]
I also like to use https://emojipedia.org/

One trick you can do when copying an emoji is to 'paste as plaintext' 

sometimes when copying an emjoi from the site it will be wrapped in a URL, so pasting in plain text will remove the URL. 

You can do this in windows by pressing `ctrl + shift + v`

Copying an emjoi from that site pretty much guarantees it will be part of the set of emjois supported within HackMD

**Comment by isss111** [comment]
@SirAh0 Thanks Brian.

I've used it, but a weird thing happens. It some places, the markdown worked, but in others, it didn't. Can you see what's happening? Thank you!

https://hackmd.io/@scrf/SkM7AVa4s

**Comment by marvino3** [comment]
This looks ready to go @SirAh0. We can add this under the Forum section. Thanks.
