### ISSUE TITLE
Updated Socials Analytics

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#364]
[SCRF Disco Analytics](https://docs.google.com/spreadsheets/d/1plvPKMFxoPl3LinYh3a7_snrlOkx4jRn9Hq22-O5Bso/edit#gid=1009764903)

**Comment by MichaelSCRF** [comment]
@marvino3: updated the podcast and Research Pulse newsletter analytics for 2022 YTD. Also added the link to the [SCRF Disco Analytics sheet](https://docs.google.com/spreadsheets/d/1plvPKMFxoPl3LinYh3a7_snrlOkx4jRn9Hq22-O5Bso/edit#gid=1009764903) to the [Analytics Meeting Guild Agenda - October 2022 #125](https://github.com/smartcontractresearchforum/IT/issues/125) GitHub board. Have not yet shared access to the sheet with participants on that board; wanted to run by that and also a couple of formulas for the SCRF Disco Analytics Sheet as part of our weekly sync.

**Comment by marvino3** [comment]
This looks great, thanks Michael
