### ISSUE TITLE
Forum Topics Imagery

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#37]
[SCRF_Web_Categories_v3.pdf](https://github.com/smartcontractresearchforum/discovery/files/8893491/SCRF_Web_Categories_v3.4.pdf)

### Related Issues
https://github.com/smartcontractresearchforum/IT/issues/45

**Comment by marvino3** [comment]
- [ ] Update forum @zubepaul 
- [ ] Update Discord emojis @SirAh0 
- [ ] Determine where to create editable templates and what size @MichaelSCRF 
- [ ] @MattDesigner please create editable templates based on specs

**Comment by SirAh0** [comment]
I updated Discord logo and bot avatars, is that what you meant by Update Discord Emjois?

@marvino3

**Comment by SirAh0** [comment]
header images need a redesign considering discourse constraints. 

feel free to reach out to me to discuss those constraints.

**Comment by marvino3** [comment]
@MattDesigner will create mockups of the forum topics headers and imagery

**Comment by MattDesigner** [comment]
Forum topics / headers mockups
https://drive.google.com/drive/u/0/folders/1xI-4pFzB9pMN5BSzM1d7GzGPXLaWVgAl

**Comment by marvino3** [comment]
great, thanks @SirAh0. sounds like we can close this issue since the design component is complete. and track it now in the new IT issue. Please let us know when you need assets.
