### ISSUE TITLE
Transcript Template

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#383]
GDoc Link: https://docs.google.com/document/d/1VhFdGFhwVx9ZFG0SKVZGD75RFUN53_XGsEa3_V-Azb0/edit

**Comment by isss111** [comment]
I don't have access to the doc.

**Comment by marvino3** [comment]
Looks great, ready to go under SCRF Docs under Docs Directory @SirAh0

**Comment by SirAh0** [comment]
done
