### ISSUE TITLE
Forum Banner Imagery

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#41]
Desc: Create editable/ templatized forum banner
Example: https://meta.discourse.org/

Currently, want to see:
- start here
- taptive cohort
- RP
- Comment of the Month

The top banner is "removable" and can be used for the Taptive Cohort:
- Join the first-ever SCRF Writing Cohort starting September 23rd
- https://scrf.io/scrf-cohort

The main banner under that can be sticky and contain the:
- start here link
- research pulse
- comment of the month

**Comment by MattDesigner** [comment]
https://drive.google.com/drive/folders/1zDatoGUPnkXc43wpXmTFC-on9ewh8Phl?usp=sharing

@marvino3 forum banners visual

**Comment by marvino3** [comment]
Perfect, thanks @MattDesigner. And thanks @zubepaul for approving the banner imagery. 

@SirAh0 could you please provide an ETA on updating these? The deadline for signing up for the Taptive cohort is this Friday, so ideally we could have this up by tomorrow.

**Comment by marvino3** [comment]
@MattDesigner can you please save down the disaggregated banner imagery as adobe and jpeg files? 
Aka the background image, the smaller banner, and the main banner with the start here, CoM, and RP as individual images

**Comment by MattDesigner** [comment]
https://drive.google.com/drive/folders/1zDatoGUPnkXc43wpXmTFC-on9ewh8Phl?usp=sharing
@marvino3 - Individual images are now in the folder. Let me know if you need anything else.

**Comment by SirAh0** [comment]
- [ ] get rid of start here banner
![image](https://user-images.githubusercontent.com/12703396/192627838-c4c0be01-e990-4101-a1a9-762493e6763e.png)

- [ ] make the start here banner persistent
- [ ] collapsed version on drill down page
- [ ] vertical align when its just the banner

**Comment by SirAh0** [comment]
**SCRF.io**
Button or something to sign up for research newsletter
signup form using substack

**Comment by marvino3** [comment]
Updated designs ready to go per @SirAh0 - https://forum.pagebrian.com/
