### ISSUE TITLE
Research Pulse Newsletter Project Proposal

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#414]
Link to doc: https://docs.google.com/document/d/1_wIk9211K3DtPvXnH6OYctki6IrAv51rzgDQFC0q_YQ/edit#

**Comment by isss111** [comment]
@marvino3 Should we add this document to the Docs Directory on Github? What's the plan?

**Comment by marvino3** [comment]
@isss111 yes, we can add this doc under a Discovery space on the Docs Directory

**Comment by isss111** [comment]
@marvino3 ready for review and PR: https://hackmd.io/@scrf/H1kM69iHs

**Comment by marvino3** [comment]
@SirAh0 this looks ready to go on Docs Directory under Discovery. 

FYI @isss111, this doc had a lot of first-person pronouns and perspectives, such as 'we', 'us', and 'ours' that I did my best to edit out. In the future, it would be awesome to have that revised before the doc gets to HackMD. Per the writing style guide, we generally want to use the third-person unless there is a good reason for first or second-person pov.

**Comment by SirAh0** [comment]
done
