### ISSUE TITLE
SCRF.io Portal Project Plan

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#417]
Link: https://docs.google.com/document/d/13o9cY3TOr9T3rKg3qcHHECnQqiTo8Vz2pfOVMNoHjdk/edit#

**Comment by isss111** [comment]
@marvino3 ready for PR: https://hackmd.io/@scrf/Sk2hkjoBj

**Comment by marvino3** [comment]
This looks ready to go. @SirAh0 can you please add this to the Docs Directory under a Discovery section? 
Side note - I think we want to alphabetize the Docs Directory except for the Archive section, which we want at the bottom of the page.

**Comment by SirAh0** [comment]
done and done.
