### ISSUE TITLE
[📣Announcement] - Discussion Writing Cohort

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/discovery#418]
### Publish Date

11/10/2022

### Highlight URL

https://scrfcohort.carrd.co/

### Announcement

✍️ Discussion Writing Cohort✍️ 
SCRF will be partnering with Taptive for another writing cohort!
This cohort will be focused on discussing scrf-interviews podcast episodes on the forum. We are looking forward to the insights gleaned from cohort discussions and the value added by participants to the conversations happening around web3 and with BlockScience.
To sign up, please fill out this form by November 25th. Got questions? Use the ❔questions or reach out to @grant or @paulzed directly.
We're looking forward to another exciting writing cohort!
https://scrfcohort.carrd.co/

**Comment by grant** [comment]
> To sign up, please fill out this form by November 25th. Got questions? Use the ❔questions or reach out to @grant or @PaulZed directly.

Please don't reach out to me, I can't help you here...

**Comment by SirAh0** [comment]
> > To sign up, please fill out this form by November 25th. Got questions? Use the ❔questions or reach out to @grant or @PaulZed directly.
> 
> Please don't reach out to me, I can't help you here...

I think the @ usernames got mixed up here between the Discord space and GitHub space as they were copy/pasted from Discord.

**Comment by SirAh0** [comment]
@zubepaul  and @marvino3 
This is a great example of why we need an announcements funnel. The writing cohort should have a dedicated informational endpoint - such as a page on scrf.io - where the individuals involved can be listed with all of their various usernames and information. 

Announcements events like this can be more uniform and point to that dedicated resource. 

Additionally, we have created an on-brand Short URL which should be used 

http://scrf.io/cohort-scrfinterviews
