### ISSUE TITLE
SCRF Performance Review Documents

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/discovery#428]

**Comment by ttaloute** [comment]
I need support with editing for clarity and grammar where it applies. Please let me know if you need more information from me. 


Performance Review Document for Team members: https://docs.google.com/document/d/1_V4REvFfWzQLOlBCHRJubKMvqkJvd9Iz8iX8v1TngoA/edit

Bounty and Grant Feedback Form: https://docs.google.com/document/d/1rDN4Z9iewl4FwzquWBOEmYxV8OfcROieXr2pxXsHcqM/edit

2022 General SCRF Form: https://docs.google.com/forms/d/1xV4pCNUDdRFZm5GEsOgokxKGGtWCNmpXTESY4uqeegM/edit

**Comment by marvino3** [comment]
Thanks Tania. Reviewed and made some edits. They look reasonable to me at this point.
