### ISSUE TITLE
Public Goods Student Association

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/discovery#436]
link to document: https://docs.google.com/document/d/1nZCjWZOIailSYrCA6PGSVzQSWTgGrOmOdt1AYp6Q924/edit#heading=h.33oflncodyhi

**Comment by isss111** [comment]
Ready for PR: https://hackmd.io/@scrf/H1tzCHSDi

**Comment by eleventh19** [comment]
Thanks! Added to [github]([project_public_goods_student_association.md](https://github.com/smartcontractresearchforum/docs/blob/main/en/project_public_goods_student_association.md)) and to the [docs page](https://github.com/smartcontractresearchforum/docs)
