### ISSUE TITLE
MVP Narrative & Navigation

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#5]
[Narrative & Navigation](https://docs.google.com/document/d/1RVCvcZPRhRSjJRfSptziAs4D9_bpDKYx7W-4-2MHKdQ/edit#heading=h.habeid6v7ruz)

Pair down the scope of our initial website navigation for an initial site release.

**Comment by SirAh0** [comment]
> @SirAh0 please help with permissions

Should be good to go, please reach out to me if you need further permissions.
