### ISSUE TITLE
Video Imagery

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#57]
- [x] Thumbnails (editable image/ templates)
- [x] Initial Bumper
- [x] End Bumper (notifications add-ons)
- [x] Speaker titles and bios
- [ ] Background imagery - animating the podcast background

- [x] #181 - now a separate issue

**Comment by marvino3** [comment]
Outstanding q - what are we doing for people who are not on camera?

**Comment by marvino3** [comment]
6/8/22 Met w @ivanplazacic @MichaelSCRF @MattDesigner 

- Photo overlay options
- Change SCRF Interviews color
- Group vs Individual speaker thumbnail options
- We love the stamps and patterns, overall template designs
- Determine if we want to specify character limits

**Comment by marvino3** [comment]
@ivanplazacic working on the video templates animation

**Comment by MichaelSCRF** [comment]
@marvino3, I think this issue is ready to be closed.

**Comment by marvino3** [comment]
Agreed, the video imagery folder can be found here - https://drive.google.com/drive/folders/106HWfBZ0hycJfPo_hD78uklbZXnOLECj?usp=sharing
