### ISSUE TITLE
Mission and Vision Statement

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#59]
Request from onboarding and engagement team

**Comment by vsterling** [comment]
@zubepaul Thanks for the clarification! I wasn't sure and just assigned @marvino3.

**Comment by vsterling** [comment]
@marvino3 or @zubepaul is there anything needed for the Mission and Vision statement? if so, please link the doc and it can be edited / posted on GitHub.

**Comment by marvino3** [comment]
@vsterling we will have a workshop around this in the coming weeks, the doc will follow. Think this is in the Team Workshop stage.

**Comment by marvino3** [comment]
Latest file - https://docs.google.com/document/d/1UV3UfvWIoXPdLc9y19qc8oospXB411pV5ahejQCrtDc/edit?usp=sharing

**Comment by isss111** [comment]
@ralphlombreglia this is ready for discovery editing. Thank you.

**Comment by marvino3** [comment]
@ralphlombreglia, thanks for looking at this. In addition to looking over the grammar/spelling, etc., which would follow the Writing Style Guide. Every doc needs to follow a SCRF GitHub Docs template for consistency.  

For this doc, you could use the [SCRF GitHub Docs General Template](https://docs.google.com/document/d/1jRbqW54KiZILDxhbQba3yC3tdfi2-fe3qItEKvYlngE/edit) as a guide. 

Therefore, every doc that goes onto GitHub, needs to have a consistent title without punctuation, a paragraph underneath explaining what the doc is about and who it is for, the body with proper headings, and then a footer. And some docs have more tailored templates like JDs and Transcripts. Happy to go over this further.

**Comment by isss111** [comment]
@marvino3 ready for review and PR. Check here: https://hackmd.io/@scrf/S1JLn01Ei

**Comment by marvino3** [comment]
Made some light edits otherwise looks good to go. @SirAh0 this is ready to go up on GitHub docs under the About SCRF section of the ToC and the Docs Directory. Thank you.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/197886994-db731f58-8a36-462e-8d89-f3945677ff05.png)

**Comment by isss111** [comment]
@SirAh0 When I click on that link, goes to https://github.com/smartcontractresearchforum/docs/blob/main/mission_and_principles.md

**Comment by marvino3** [comment]
I believe this has been updated on /docs
