### ISSUE TITLE
GitHub Discovery Questions

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#60]
[Discovery PM Qs](https://docs.google.com/document/d/15dzDVUncn5GjDnfIZTXlHaYDwnX1nykKKJBzzyM-QIQ/edit)

Please see New Questions at the bottom of the doc. These include:

- [x] How to link issues back to epics/ projects? Same repo or between repos?
`Answer: 'copy link' and then add it to any board or other repo`

- [x] Do we want to have one repo for SCRF overall? Is there a good reason to have multiple repos? 
`Answer: Multiple repos bc we want to differentiate bw private and public and based on management. As long as we maintain the docs repo.`

- [x] How do I move and connect issues between repos if that is what we decide to go with? Ex: use scrf.io repo for all website project management tracking but then how do I link issues back to the Design Discovery board to see all Design needs in one spot?
`Answer: 'copy link' and then add it to any board or other repo`

- [x] Can I update multiple things at once? Aka convert multiple drafts into issues? Single select a category for multiple cells?
> convert drafts to issues, don't think so. 
> Moving things around on a project board? yes, you can click the first item in the list, hold shift, and click the last item in the list. you can then drag move the bunch. You can also hold shift and left click on a card to group select individually. 
> For more tips, check out the [GitHub Docs on Tracking Projects](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/tracking-work-with-project-boards/adding-issues-and-pull-requests-to-a-project-board)
> @SirAh0 

- [x] Can I view and hide certain columns on a Board? (ex: Marketing Board sorting for properties and hiding all columns until I just see Forum and Discord)
> You can drag columns around and re-order them. Place the ones you want to see first and save the view. 
> Another approach could be to create a new view. 
> Please feel free to follow up with me if you need more help.
> [💾 GitHub Project Board](https://github.com/smartcontractresearchforum/IT/issues/new/choose)
> @SirAh0 

- [x] How to capture MVP, v1, v2, etc?

- [x] Can we use 'or' statements for filtering withint github boards? Ex: filter and show cards that have 'properties' set to 'socials' or 'twitter' or 'linkedin' under discovery
> GitHub can only filter using 'and' logic. each filter is separated by a space.
> See [Syntax for filtering projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/filtering-projects#syntax-for-filtering-projects)
>@sirah0

- [x] Is it possible to create request templates that link to same or different boards and potentially repos? Ex: design request has its own template and that auto goes to a design board/ messaging request has its own template and that goes to a messaging board

> yes, if you would like a custom issue please open a request here:
> [💾 GitHub Issue Template](https://github.com/smartcontractresearchforum/IT/issues/new/choose)
> @sirah0

**Comment by marvino3** [comment]
@SirAh0 @twan-dev were you able to answer any of these questions? Thanks!

**Comment by marvino3** [comment]
- Can I create an issue from a task list?

**Comment by SirAh0** [comment]
> * Can I create an issue from a task list?

Yes, you can. The task list has to live in the main body of the issue, not a comment.
>If a task requires further tracking or discussion, you can convert the task to an issue by hovering over the task and clicking  in the upper-right corner of the task. To add more details before creating the issue, you can use keyboard shortcuts to open the new issue form. For more information, see "[Keyboard shortcuts](https://docs.github.com/en/github/getting-started-with-github/using-github/keyboard-shortcuts#issues-and-pull-requests)."
