### ISSUE TITLE
Research Pulse Newsletter

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#61]
- [x] Create brainstorming document with questions and needs for initial meeting with Maria, Ralph, and Michael - @MichaelSCRF - [Research Pulse Newsletter Exploratory Meeting - July 6, 2022](https://docs.google.com/document/d/1q0PRG9kxJuZTnxnjigJJuItf7siZrfLR4S7wp8JcuoU/edit#)
- [x] Schedule initial meeting with Maria, Ralph, and Michael - @MichaelSCRF
- [x] Create a Project Plan for the Research Pulse newsletter, per Maria's Discord messages @MichaelSCRF - [Research Pulse Newsletter Project Proposal](https://docs.google.com/document/d/1_wIk9211K3DtPvXnH6OYctki6IrAv51rzgDQFC0q_YQ/edit#heading=h.9xvwuxmfaxqg)
- [x] Create a weekly standing meeting to discuss the Research Pulse newsletter launch @MichaelSCRF 
- [x] Meet to answer questions and needs and crystalize an outline plan for future discussion with senior leadership - @MichaelSCRF, @marvino3, @ralphlombreglia 
- [x] Review Ralph's Mirror and Substack mock-ups and take notes - @MichaelSCRF, @marvino3 
- [x] Determine process for signing up for a SCRF Mirror account, especially wallet implementation, with Core Ops - @MichaelSCRF, @marvino3 
- [x] Send Michael the specs for Mirror and Substack banner images, respectively @ralphlombreglia 
- [x] Edit the Research Pulse image template for use as Mirror and Substack banner images and send them to Ralph @MichaelSCRF 
- [x] Reach out to Paul and let him know that we'd like to promote the newsletter and encourage community members to sign up via Discord, and also that we would like his feedback on the first test email @MichaelSCRF 
- [x] Write copy to share the Research Pulse newsletter with the community via Discord @MichaelSCRF 
- [x] Create a test version of the Research Pulse newsletter utilizing the content from RP #s 80 and 81, and send it to RP team, core ops, and Paul @ralphlombreglia 
- [x] Finalize mission text for "About SCRF" footer @MichaelSCRF @marvino3
- [x] Share the Research Pulse newsletter with the community via Discord and promote subscription sign-ups, starting with RP# 81 @MichaelSCRF 
- [x] Publicize the newsletter in the PPP meeting and Community Call on September 7 and 8, respectively @MichaelSCRF 
- [x] Send RPs 81 and 82 to subscribers and core team members as part of the soft launch/feedback period @ralphlombreglia, @MichaelSCRF 

Description: At SCRF, our intention is to create a Research Pulse newsletter to deliver the value of the RP to content consumers over time. At the moment, the chosen articles live in a forum post and we drive traffic with socials. However, news digest tends to work well with newsletters so consumers can view these over time, have predictable notifications, and access to prior content. 

We have started to brainstorm [Here](https://docs.google.com/document/d/1d3LPqb9YUt8atmI3sq8FgbbAfthZxuJIVqysG8E-L4E/edit?usp=sharing)

Initial Objectives:
- Explanatory text and info around the research pulse activity 
- Here are the 5 papers and here are the author comments

Addressable Market - All of Web3
- Give appreciation to the researchers/ authors
- RT faculty, universities, etc.

Needs: Web3 Expert Resource

**Comment by marvino3** [comment]
Shared the [Research Pulse Newsletter Project Proposal](https://docs.google.com/document/d/1_wIk9211K3DtPvXnH6OYctki6IrAv51rzgDQFC0q_YQ/edit#heading=h.9xvwuxmfaxqg) with @ghettodev @eleventh19 @zubepaul @twan-dev for comments/ thoughts by Fri, Jul 22

**Comment by MichaelSCRF** [comment]
@ralphlombreglia and @marvino3:

Some feedback on the Research Pulse #79 Test Runs:

I think the Mirror version looks great all around.

For the Substack version:

- I think the banner looks good with the limited real estate we have as a result of the Substack banner specs
- Can we have some intro text under the banner but above the Issue Number headline that says "Dig into a weekly list of notable web3 research"? I think that tag line is important to both the branding and contextualization of the newsletter.
- @ralphlombreglia, I am having the same issue with the sans serif font in the email and the serif font in the browser. Personally, I think the sans serif font is cleaner and more readable, but ultimately, I think that any customizable decisions we make about the RP newsletter typeface should be aligned with whatever branding decisions associated with typeface we've already made for SCRF.io. @marvino3, do you have any insights or thoughts on this?
- The "About SCRF" messaging in both versions of the newsletter needs to be one of the following two pieces of copy:

The [Smart Contract Research Forum (SCRF)](https://www.smartcontractresearch.org/) is a grants-funded organization dedicated to advancing research while serving the web3 space.

OR

The [Smart Contract Research Forum (SCRF)](https://www.smartcontractresearch.org/) is a grants-funded organization dedicated to advancing research while serving the web3 space. In support of its mission, SCRF distributes grants, sponsors projects, facilitates resources, and provides operational support to organizations and independent researchers who create or use actionable research.

**Comment by MichaelSCRF** [comment]
@ralphlombreglia and @marvino3:

I've drafted some copy for the Discord announcement of the soft launch of the newsletter to the SCRF community. [Here](https://docs.google.com/document/d/1QGa7vtZaG6uSXks8oO6D5ew1YQc-2Vg6kpTIF8jQnVE/edit) is a Google Document containing the copy, and it is also below:

Hello at-everyone. The Discovery Team is excited to announce the soft launch to the SCRF community of our new Research Pulse newsletter, and we’d like to invite you all to subscribe. To this point, Research Pulse has been one of our primary outlets for sharing the latest web3 research via socials and the forum on a weekly basis. Based on the positive engagement with Research Pulse we’ve received via both of these channels, we’re committed to further promoting the groundbreaking research that is happening in the space by giving readers an opportunity to either have it emailed to their inbox every week via Substack, or to receive a weekly  update that a new issue of the newsletter is published and available to read on Mirror. Our hope is that this will make it even more convenient for current Research Pulse readers to dig into this curated research each week, and that it will also attract new readers who don’t yet know about Research Pulse but are interested in keeping up with current web3 research.

You can subscribe to the free Research Pulse Newsletter in one of two ways:

1. Subscribe to the e-newsletter via Substack at the following link: [LINK]
2. Subscribe via Mirror by connecting a crypto wallet at the following link: [LINK]

Thank you in advance for subscribing, and, please let us know if you have any feedback or suggestions regarding the newsletter. As part of the soft launch process, we’d like to publish a few issues exclusively for the SCRF community as a test run to give ourselves the opportunity to troubleshoot and work out any bugs before we publicize the newsletter to the greater community, while simultaneously maintaining our current public Research Pulse presence via socials and the forum. Your reactions during this soft launch phase are invaluable in helping us to fully migrate Research Pulse to the newsletter format and publicize it to the greater community in the coming weeks.

**Comment by marvino3** [comment]
RP has been launched!
