### ISSUE TITLE
Docs README page

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#64]
Suggested updates to the [Docs README and folder system](https://docs.google.com/document/d/1CJDTt9BL5OeEWKOPQ6IzbhtNAjxZbRlHOfuN-L0qkMQ/edit?usp=sharing)

**Comment by vsterling** [comment]
Captured and replaced with #19

**Comment by isss111** [comment]
@marvino3 sharing here an updated version of the Docs README page: https://docs.google.com/document/d/1CJDTt9BL5OeEWKOPQ6IzbhtNAjxZbRlHOfuN-L0qkMQ/edit#

**Comment by isss111** [comment]
@SirAh0 do you mind taking out the "Grants, Bounties, and Awards" section of the readme? 
 Cc/ @marvino3

**Comment by SirAh0** [comment]
updated
