### ISSUE TITLE
Upload SCRF Deck Template

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#66]
[SCRF Deck Template]

Needs to be added to the assets/ design folder

**Comment by marvino3** [comment]
@MattDesigner please update the 'Title and Content' and 'Title Slide 1' in the Theme Builder https://docs.google.com/presentation/d/1RjtXSyhOgRIVvAEAYKHd47NmxaJAtjKTrt4DKR__u7M/edit?usp=sharing

**Comment by marvino3** [comment]
Ack, updated link - https://docs.google.com/presentation/d/1hS1p1f8Tr-yn4sizwjlAHWEXT4ZFFq8fWW2lU75egEg/edit?usp=sharing

**Comment by SirAh0** [comment]
done

![image](https://user-images.githubusercontent.com/12703396/174688209-b108f2d4-3624-4974-9a85-44d35a7424d4.png)

**Comment by vsterling** [comment]
@SirAh0 How do I create a PR for this kind of media? Not sure about the file naming or how exactly to upload to assets.

**Comment by marvino3** [comment]
@SirAh0 can you please send an update on how we can add this to the [Brand Assets](https://github.com/smartcontractresearchforum/docs/tree/main/assets/brand) folder on GitHub docs?

**Comment by SirAh0** [comment]
hmm good question. I'm sure google offers this in some kind of downloadable format, I'll look into it.

**Comment by SirAh0** [comment]
done!
https://github.com/smartcontractresearchforum/docs/blob/main/assets/brand/Presentation%20Theme.pdf
