### ISSUE TITLE
Migrate scrf.io issues to discovery repo

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#67]
https://github.com/orgs/smartcontractresearchforum/projects/11/views/1

**Comment by marvino3** [comment]
Nice, thanks @SirAh0. I think #68 is a general GitHub ask. Not sure where we are capturing those. But it doesn't need to live on the scrf.io board view.

For #69 though, can you please update this issue so it shows up in the scrf,io view? https://github.com/orgs/smartcontractresearchforum/projects/17/views/13

**Comment by SirAh0** [comment]
done

![image](https://user-images.githubusercontent.com/12703396/173876968-8f9f43c7-fe28-4719-8205-414ae9198703.png)
