### ISSUE TITLE
Discord Colors and Patterns

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#70]
**IT Repo**
[🗪 [🚧] Role Color Change](https://github.com/smartcontractresearchforum/engagement/issues/30)

https://docs.google.com/document/d/1_6v1vVUEV12UpSP8hN0Fq-TmvgHWEIejuiv6Cz1h23E/edit#heading=h.8ot4nu9vrtie

**Comment by marvino3** [comment]
Meet with @SirAh0 to discuss on 6/7/22

[SCRF_Discord_colours v2.pdf](https://github.com/smartcontractresearchforum/discovery/files/8826772/SCRF_Discord_colours.v2.pdf)

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/173669565-5d4c8613-3b97-457b-9fb2-e06bbcc7ed35.png)
