### ISSUE TITLE
SCRF AMA

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#71]
First one AMA is with Chainlink on June 9th - did not happen
Moved to June 16th

- [x] Create a new ticket to create a SCRF Reddit
- [x] Help manage AMA
- [x] Promote ahead of time - from SCRF and from Chainlink
- [x] Promote post AMA

[One Pager](https://docs.google.com/document/d/16xOlsUIjov0YtRfPrQpLRYf0c_5-UBOceh8qQdiYX_4/edit?usp=sharing)

**Comment by MichaelSCRF** [comment]
Promotion and moderation of the June 16 AMA is completed. Do we still want to create a SCRF subreddit? I know there was some debate as to whether that might unintentionally drive traffic away from the forum itself.

**Comment by marvino3** [comment]
Good q. I think we can table that discussion for now and close out this ticket. And create a new one to capture a SCRF subreddit as an idea.

**Comment by MichaelSCRF** [comment]
Sounds good, thanks Maria! I will move this to "Done" and create a SCRF subreddit
