### ISSUE TITLE
Blockchain Research Mentor JD

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/discovery#75]
The JDs for a ["Peer Reviewer"](https://github.com/smartcontractresearchforum/docs/blob/main/en/hiring_peer_reviewer.md) and ["Research Project Manager"](https://github.com/smartcontractresearchforum/docs/blob/main/en/hiring_research_project_management.md) are both very outdated, and could be replace by (the temporarily dubbed) "[Blockchain Research Mentor"](https://docs.google.com/document/d/1sDOtTLboi90rDuRFKxPdzzaOXM7yy6lzTtAs36IKAl0/edit#)

**Comment by vsterling** [comment]
Created new copy of the [Blockchain Research Mentor JD](https://docs.google.com/document/d/1E4qjzJt2NeMD9PUkzcyVxeXVOZpvLkhSovO9TxvemlI/edit?usp=sharing) for editing. @twan-dev -- this just needs your final say and approval of minor changes. Then can go live.

**Comment by vsterling** [comment]
Reviewed and approved by Twan. 
@ghettodev PRs were created to add the JD [#51](https://github.com/smartcontractresearchforum/docs/pull/50) and update the info in the Docs ReadMe [#50](https://github.com/smartcontractresearchforum/docs/pull/50)

**Comment by vsterling** [comment]
Created [PR 57](https://github.com/smartcontractresearchforum/docs/pull/57) that address @ghettodev's changes. Ready for review.

**Comment by vsterling** [comment]
The [Blockchain Research Mentor](https://github.com/smartcontractresearchforum/docs/blob/main/en/hiring_blockchain_research_mentor.md) is now live. (I just created a [PR 62](https://github.com/smartcontractresearchforum/docs/pull/62) to list it to the ReadMe.)

**Comment by vsterling** [comment]
JD added to the [ReadMe](https://github.com/smartcontractresearchforum/docs)
