### ISSUE TITLE
Youtube Socials Implementation

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#76]
- [x] Strategy Doc
- [x] Stakeholder Breakout @ivanplazacic @MichaelSCRF @MattDesigner 
- [x] Incorporate feedback and add to overall Socials Project Plan
- [x] #57 
- [x] @MichaelSCRF creates youtube example which @ivanplazacic and @marvino3 review
- [ ] #170

**Comment by MichaelSCRF** [comment]
This ticket can be closed out. Created new tickets to:

- [Update YouTube Homepage](https://github.com/smartcontractresearchforum/discovery/issues/170)
- [Update the Old YouTube Videos](https://github.com/smartcontractresearchforum/discovery/issues/171)
- [Update the YouTube section of the Socials Project Plan](https://github.com/smartcontractresearchforum/discovery/issues/84)
