### ISSUE TITLE
Twitter Web3 News & Trends

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#82]
[Web3 News & Trends Brainstorm](https://docs.google.com/document/d/1d3LPqb9YUt8atmI3sq8FgbbAfthZxuJIVqysG8E-L4E/edit?usp=sharing)

**Comment by marvino3** [comment]
- [ ] Incorporate Web3 news/ trends takeaways into Loomly @MichaelSCRF 
- [ ] Incorporate into overall socials strategy doc @MichaelSCRF 
- [ ] Gathering feedback for news sources from core ops @marvino3 
- [ ] Review strategy, finalize, operationalize

**Comment by MichaelSCRF** [comment]
[Here](https://docs.google.com/document/d/1Ucc_-4z9JZrR6kud5RpVqYsfsjaOb9UHarhX1-DYFSU/edit?usp=sharing) is the final mapping doc.
