### ISSUE TITLE
scrf.io v1 Prototype

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#93]
Description: This issue is for scrf.io prototypes. After we decide on wireframes, we will want to create the draft prototypes, which will include:

- [x] #7 
- [x] #8

**Comment by SirAh0** [comment]
I'm assigned to this issue but I'm not sure what I should do.

**Comment by SirAh0** [comment]
![6k2iib](https://user-images.githubusercontent.com/12703396/174424206-b3814326-bf05-477d-b9c1-b9ccec92791c.gif)

**Comment by marvino3** [comment]
@SirAh0 I believe this ticket is capturing the tech prototype for v1 scrf.io site based on the following mockup - [SCRF Website Mockup](https://drive.google.com/file/d/14jSLU0QicH9aKvPxxxsMX6KoV7AfnxGy/view?usp=sharing)


The Researchers section is missing and will be under the Researcher/Builder bridge image and before the Builder section right below it
